### PR TITLE
Fix to issue #41

### LINKED ISSUE #41: Setup script cannot be run
I get the following error message when I try to run the setup script. 

screen shot 2016-03-28 at 18 26 51

BTW: Jan, that was after your last PR.

### PR DESCRIPTION
**Pull request by janlav**
* Fixes #41 - fixed bug which prevented using structures missing version-numbers in updateRapidSettings.m

* Added so that systems when "hiding" simulink-system that is already opened nothing is saved unless it is "dirty" in Rapid.m

### CODE REVIEW

**Comment by MaximeBaudette** [comment]
>Added so that systems when "hiding" simulink-system that is already opened nothing is saved unless it is "dirty" in Rapid.m

What do you mean by that?

File: rapid/core/@RaPIdClass/updateRapidSettings.m [hunk 1]
```diff
@@ -1,9 +1,13 @@
 function  obj = updateRapidSettings(obj,oldThing)
 % UPDATERAPIDOBJ this function will update old rapid-objects
 %   Detailed explanation goes here
-objversion=oldThing.version; %old version number
+if isfield(oldThing,'version') || isprop(oldThing,'version')
+    objversion=oldThing.version; %old version number
+else % we are dealing with a struct with no version, probably user forgot this
+    objversion=1.41; % we assume that we conform to latest version
```
Comment (MaximeBaudette) [inline rapid/core/@RaPIdClass/updateRapidSettings.m]: Is hard-coding this the only solution ?

**Comment by tinrabuzin** [comment]
@MaximeBaudette This was assigned to me! :)

**Comment by MaximeBaudette** [comment]
@tinrabuzin 
Sorry,  Jan sent me a message yesterday and told me to take care of it, so I did it.

**Comment by MaximeBaudette** [comment]
@tinrabuzin 
:-P

**Comment by tinrabuzin** [comment]
@MaximeBaudette I guess I'm too slow for such rapid development process. :) Sorry @janlav
